version: v2
managed:
  enabled: true
plugins:
  - remote: buf.build/grpc-ecosystem/openapiv2:v2.25.1
    out: ../tui/gen
    opt:
      - logtostderr=true
      - output_format=yaml
      - allow_merge=true,merge_file_name=openapi
